apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: generador-reportes-ventas
  name: generador-reportes-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: generador-reportes-ventas
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: generador-reportes-ventas
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: ventas_servicio_db
            - name: DB_NAME
              value: ventas_servicio_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: generador-reportes-ventas
          name: generador-reportes-ventas
          ports:
            - containerPort: 3007
              protocol: TCP
      restartPolicy: Always
