apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gestor-productos
  name: gestor-productos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gestor-productos
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: gestor-productos
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: inventario_servicio_db
            - name: DB_NAME
              value: inventario_servicio_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
          image: gestor-productos
          name: gestor-productos
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
