apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gestor-usuarios
  name: gestor-usuarios
spec:
  ports:
    - name: "3011"
      port: 3011
      targetPort: 3011
  selector:
    io.kompose.service: gestor-usuarios
