apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gestor-ventas
  name: gestor-ventas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gestor-ventas
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: gestor-ventas
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: ventas_servicio_db
            - name: DB_NAME
              value: ventas_servicio_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: STOCK_HOST
              value: gestor-stock
            - name: STOCK_PORT
              value: "3002"
            - name: USUARIOS_HOST
              value: gestor-usuarios
            - name: USUARIOS_PORT
              value: "3011"
          image: us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/gestor_ventas:${TAG}
          name: gestor-ventas
          ports:
            - containerPort: 3008
              protocol: TCP
      restartPolicy: Always
