apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestor-entregas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gestor-entregas
  template:
    metadata:
      labels:
        io.kompose.service: gestor-entregas
    spec:
      containers:
        - name: gestor-entregas
          image: us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/gestor_entregas:${TAG}
          ports:
            - containerPort: 3006
          env:
            - name: DB_HOSTNAME
              value: logistica-servicio-db
            - name: DB_NAME
              value: logistica_servicio_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: PULSAR_HOST
              value: pulsar
            - name: USUARIOS_HOST
              value: gestor-usuarios
            - name: USUARIOS_PORT
              value: "3011"
            - name: PRODUCTOS_HOST
              value: gestor-productos
            - name: PRODUCTOS_PORT
              value: "3001"
            - name: GENERADOR_RUTAS_HOSTNAME
              value: generador-rutas-entrega
            - name: GENERADOR_RUTAS_PORT
              value: "3005"
        - name: sidecar
          image: us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/sidecar:latest
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOSTNAME
              value: logistica-servicio-db
            - name: DB_NAME
              value: logistica_servicio_db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: GENERADOR_RUTAS_HOSTNAME
              value: generador-rutas-entrega
            - name: GENERADOR_RUTAS_PORT
              value: "3005"
