apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: gestor-proveedores
  name: gestor-proveedores
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gestor-proveedores
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: gestor-proveedores
    spec:
      containers:
        - env:
            - name: DB_HOSTNAME
              value: inventario-servicio-db
            - name: DB_NAME
              value: inventario-servicio-db
            - name: DB_PASSWORD
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: PULSAR_HOST
              value: pulsar
          image: us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_proveedores:${TAG}
          name: gestor-proveedores
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always
