apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: logistica-servicio-db
  name: logistica-servicio-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logistica-servicio-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: logistica-servicio-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: logistica_servicio_db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 5
            periodSeconds: 2
            timeoutSeconds: 5
          name: logistica-servicio-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
