apiVersion: v1
kind: Service
metadata:
  name: pulsar
spec:
  type: ClusterIP
  selector:
    app: pulsar
  ports:
    - name: broker
      port: 6650
      targetPort: broker
    - name: admin
      port: 8080
      targetPort: admin