openapi: 3.0.0
info:
  title: API de Registro de Pedidos de Clientes
  description: |
    API para que los vendedores puedan registrar pedidos en línea desde dispositivos móviles
  version: 1.0.0
servers:
  - url: http://RUTA_GCP/api/v1/ventas/procesador_pedidos
    description: Servidor de producción
  - url: http://127.0.0.1:3009/api/v1/ventas/procesador_pedidos
    description: Servidor de desarrollo
paths:
  /pedidos:
    post:
      tags:
        - pedidos
      summary: Registrar un nuevo pedido de cliente
      description: |
        Crea un nuevo pedido para un cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PedidoInput'
      responses:
        '201':
          description: Pedido registrado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PedidoResponse'
        '400':
          description: Error en la validación de datos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Cliente o producto no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Stock insuficiente para uno o más productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockErrorResponse'
        '429':
          description: Demasiadas solicitudes, se ha superado el límite de procesamiento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:
    PedidoInput:
      type: object
      required:
        - cliente_id
        - productos
      properties:
        cliente_id:
          type: integer
          format: int64
          example: 123456
          description: Identificador único del cliente que realiza el pedido
        vendedor_id:
          type: integer
          format: int64
          example: 987654
          description: Identificador único del vendedor que registra el pedido
        productos:
          type: array
          description: Lista de productos incluidos en el pedido
          items:
            type: object
            required:
              - id
              - cantidad
            properties:
              id:
                type: integer
                example: 12345
                description: Identificador único del producto
              cantidad:
                type: integer
                minimum: 1
                example: 10
                description: Cantidad solicitada del producto
              precio_unitario:
                type: number
                format: float
                example: 10000
                description: Precio unitario aplicado al producto
          minItems: 1

    PedidoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123456
          description: Identificador único del pedido generado
        cliente_id:
          type: integer
          format: int64
          example: 123456
        fecha_creacion:
          type: string
          format: date-time
          example: "2025-03-25T10:30:00Z"
          description: Fecha y hora de creación del pedido
        estado:
          type: string
          enum: [pendiente, confirmado, en_proceso, en_ruta, entregado, cancelado]
          example: "pendiente"
          description: Estado actual del pedido
        productos:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 12345
              nombre:
                type: string
                example: "Producto Uno"
              cantidad:
                type: integer
                example: 10
              precio_unitario:
                type: number
                format: float
                example: 10000
              subtotal:
                type: number
                format: float
                example: 100000
        subtotal:
          type: number
          format: float
          example: 300000
          description: Subtotal del pedido
        total:
          type: number
          format: float
          example: 342000
          description: Monto total del pedido

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Datos inválidos"
        detalles:
          type: object
          additionalProperties:
            type: string
          example:
            cliente_id: "El cliente no existe"
            productos: "Se requiere al menos un producto"

    StockErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Stock insuficiente"
        productos_sin_stock:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                example: 12345
              nombre:
                type: string
                example: "Producto Uno"
              stock_disponible:
                type: integer
                example: 5
              cantidad_solicitada:
                type: integer
                example: 10

    ServerErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error interno del servidor"
        message:
          type: string
          example: "Ha ocurrido un error procesando su solicitud. Por favor, inténtelo más tarde."
        reference_id:
          type: string
          format: uuid
          example: "987a6543-b21c-09d8-e765-432109fedcba"
          description: Identificador de referencia para el seguimiento del error