
curl -X POST "http://127.0.0.1:5000/api/v1/ventas/gestor_planes_venta/visita_cliente" \
-H "Content-Type: application/json" \
-d '{
  "cliente_id": 1,
  "vendedor_id": 1,
  "fecha": "2025-05-31T00:00:00.000Z",
  "ubicacion_productos_ccp": [
    {"id_producto": 1, "ubicacion": "caja"}
  ],
  "ubicacion_productos_compentencia": [
    {"id_producto": 1, "ubicacion":"pasillo_principal"}
  ]
}'