openapi: 3.0.3
info:
  title: Consultar el listado de clientes
  version: 1.0.0
  description: API para la consulta de clientes

paths:
  /api/v1/seguridad/gestor_usuarios/r/clientes:
    get:
      summary: Consulta listado de clientes
      operationId: queryClient
      responses:
        "200":
          description: Usuarios consutlados exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientesResponse'
        "400":
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ClientesResponse:
      type: object
      properties:
        clientes:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int64
                example: 123456
              name:
                type: string
                example: "John Doe"
              email:
                type: string
                format: email
                example: "john.doe@example.com"
              country:
                type: string
                example: "Colombia"
              city:
                type: string
                example: "Bogota"
              address:
                type: string
                example: "CL 1 # 2 - 3"
      example:
        clientes:
          - id: 123456
            name: "John Doe"
            email: "john.doe@example.com"
            country: "Colombia"
            city: "Bogota"
            address: "CL 1 # 2 - 3"
          - id: 789012
            name: "Jane Smith"
            email: "jane.smith@example.com"
            country: "Colombia"
            city: "Medellin"
            address: "CL 4 # 5 - 6"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Error en la solicitud"