openapi: 3.0.3
info:
  title: Consultar el listado de clientes
  version: 1.0.0
  description: API para la consulta de clientes

paths:
  /api/v1/seguridad/gestor_usuarios/r/clientes:
    get:
      summary: Consulta listado de clientes
      operationId: queryClient
      responses:
        "200":
          description: Usuarios consutlados exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientesResponse'
        "400":
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ClientesResponse:
      type: object
      required:
        - id
        - name
        - email
        - country
        - city
        - address
      properties:
        id: 
          type: integer
          format: int64
          example: 123456
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john.doe@example.com"

        country:
          type: string
          example: "Colombia"
        city:
          type: string
          example: "Bogota"
        address:
          type: string
          example: "CL 1 # 2 - 3"

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Error en la solicitud"