openapi: 3.0.0
info:
  title: API de consulta de camiones
  description: |
    API para consultar la lista de camiones disponibles en el sistema.
  version: 1.0.0
servers:
  - url: http://RUTA_GCP/api/v1/logistica/gestor_entregas/ruta_camiones
    description: Servidor de producción
  - url: http://127.0.0.1:3006/api/v1/logistica/gestor_entregas/ruta_camiones
    description: Servidor de desarrollo
paths:
  /ruta_camiones:
    get:
      tags:
        - camiones
      summary: Consultar camiones y sus rutas
      description: |
        Obtiene la lista de camiones disponibles en el sistema junto con su estado de enrutamiento para una fecha específica. Si no se proporciona una fecha, se utiliza la fecha actual.
      parameters:
        - name: fecha
          in: query
          description: Fecha para filtrar los camiones y sus rutas (formato YYYY-MM-DD). Si no se proporciona, se usa la fecha actual.
          required: false
          schema:
            type: string
            format: date
            example: "2025-05-12"
      responses:
        '200':
          description: Lista de camiones obtenida exitosamente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CamionesResponse'
        '400':
          description: Error en la solicitud debido a un formato de fecha inválido.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestResponse'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:
    CamionesResponse:
      type: object
      properties:
        total:
          type: integer
          example: 2
          description: Número total de camiones.
        camiones:
          type: array
          items:
            $ref: '#/components/schemas/CamionDetalle'
          description: Lista de camiones con sus detalles y estado de enrutamiento.
    CamionDetalle:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: Identificador único del camión.
        placa:
          type: string
          example: "ABC123"
          description: Placa del camión.
        marca:
          type: string
          example: "Volvo"
          description: Marca del camión.
        modelo:
          type: string
          example: "FH"
          description: Modelo del camión.
        capacidad_carga_toneladas:
          type: number
          format: float
          example: 20.0
          description: Capacidad de carga en toneladas.
        volumen_carga_metros_cubicos:
          type: number
          format: float
          example: 50.0
          description: Volumen de carga en metros cúbicos.
        estado_enrutamiento:
          type: string
          example: "Sin entregas programadas"
          description: Estado de enrutamiento del camión para la fecha especificada.
    BadRequestResponse:
      type: object
      properties:
        error:
          type: string
          example: "Formato de fecha inválido. Use el formato YYYY-MM-DD."
          description: Descripción del error.
    ServerErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error interno del servidor"
          description: Descripción general del error.
        message:
          type: string
          example: "Error inesperado en el servidor."
          description: Detalles del error interno.
