openapi: 3.0.0
info:
  title: API de consulta de estados de entregas
  description: |
    API para que clientes de CCP puedan consultar el estado actual de sus entregas.
  version: 1.0.0
servers:
  - url: http://RUTA_GCP/api/v1/logistica/gestor_entregas
    description: Servidor de producción
  - url: http://127.0.0.1:3009/api/v1/logistica/gestor_entregas
    description: Servidor de desarrollo
paths:
  /:
    get:
      tags:
        - entregas
      summary: Consultar entregas
      description: |
        Obtiene la lista de entregas del cliente con sus estados actuales.
      parameters:
        - name: cliente_id
          in: query
          required: true
          description: ID del cliente que está consultando sus entregas
          schema:
            type: integer
            format: int64
            example: 123456

      responses:
        '200':
          description: Lista de entregas obtenida exitosamente (puede estar vacía si el cliente no tiene entregas)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntregasResponse'
        '404':
          description: Cliente no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteNoEncontradoResponse'
        '500':
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'
  
components:
  schemas:
    EntregasResponse:
      type: object
      properties:
        total:
          type: integer
          example: 42
          description: Número total de entregas
        pages:
          type: integer
          example: 5
          description: Número total de páginas disponibles
        current_page:
          type: integer
          example: 1
          description: Página actual que se está mostrando
        entregas:
          type: array
          items:
            $ref: '#/components/schemas/EntregasResumen'
          description: Lista de entregas
    
    EntregasResumen:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123456
          description: Identificador único del entrega
        fecha_entrega:
          type: string
          format: date
          example: "2025-05-31"
          description: Fecha programada de entrega del entrega
        hora_entrega:
          type: string
          format: time
          example: "14:30"
          description: Hora programada de entrega del entrega
        cantidad_productos:
          type: integer
          example: 10
          description: Cantidad total de productos en el entrega
        valor_total:
          type: number
          format: float
          example: 150.75
          description: Valor total del entrega

    ClienteNoEncontradoResponse:
      type: object
      properties:
        error:
          type: string
          example: "Cliente no encontrado"
          description: Descripción general del error
        message:
          type: string
          example: "No se encontró el cliente con el ID especificado"
          description: Mensaje informativo para el usuario
    
    ServerErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error interno del servidor"
          description: Descripción general del error
        message:
          type: string
          example: "Ha ocurrido un error procesando su solicitud. Por favor, inténtelo más tarde."
          description: Mensaje para el usuario