FROM python:3.10-slim

WORKDIR /app

COPY backend/logistica_servicio/generador_rutas_entrega/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/logistica_servicio/generador_rutas_entrega /app/
COPY backend/seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH}"

# Expose port 3005
EXPOSE 3005

# Define the start command
CMD ["python", "app.py"]