FROM python:3.10

WORKDIR /app

COPY backend/inventario_servicio/gestor_productos/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/inventario_servicio/gestor_productos /app/
COPY backend/seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH}"

# Expose port 3001
EXPOSE 3001

# Define the start command
CMD ["python", "app.py"]