FROM python:3.10-slim

WORKDIR /app

COPY ../compras_servicio/gestor_compras/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../compras_servicio/gestor_compras /app/
COPY seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH:-}"

# Expose port 3000
EXPOSE 3000

# Define the start command
CMD ["python", "app.py"]