FROM python:3.10-slim

WORKDIR /app

COPY backend/ventas_servicio/procesador_video/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ventas_servicio/procesador_video /app/
COPY backend/seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH}"

# Expose port 3010
EXPOSE 3010

# Define the start command
CMD ["python", "app.py"]