FROM python:3.10

WORKDIR /app

COPY backend/ventas_servicio/generador_reportes/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ventas_servicio/generador_reportes /app/
COPY backend/seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH}"

# Expose port 3007
EXPOSE 3007

# Define the start command
CMD ["python", "app.py"]