FROM python:3.10-slim

WORKDIR /app

COPY backend/inventario_servicio/gestor_productos/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/inventario_servicio/gestor_productos /app/gestor_productos

# Expose port 3001
EXPOSE 3001

# Define the start command
CMD ["python", "gestor_productos/app.py"]