FROM python:3.10-slim

WORKDIR /app

COPY ../inventario_servicio/gestor_stock/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../inventario_servicio/gestor_stock /app/
COPY seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH:-}"

# Expose port 3002
EXPOSE 3002

# Define the start command
CMD ["python", "app.py"]