FROM python:3.10-slim

WORKDIR /app

COPY backend/seguridad_servicio/gestor_usuarios/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

#COPY backend/seguridad_servicio/gestor_usuarios /app/
COPY backend/seguridad_servicio/gestor_usuarios /app/gestor_usuarios

ENV PYTHONPATH="/app"

# Expose port 3011
EXPOSE 3011

# Define the start command
CMD ["python", "gestor_usuarios/app.py"]