FROM python:3.10-slim

WORKDIR /app

COPY ../logistica_servicio/gestor_entregas/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../logistica_servicio/gestor_entregas /app/
COPY seedwork_compartido /app/seedwork_compartido

ENV PYTHONPATH="/app/seedwork_compartido:${PYTHONPATH:-}"

# Expose port 3006
EXPOSE 3006

# Define the start command
CMD ["python", "app.py"]