curl --location 'http://34.8.66.38/api/v1/ventas/procesador_pedidos/pedidos?cliente_id=28' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzQ0MzUwMDAyfQ.N37zn6lyZctrMoH9z9JRXG8BTvPbnSX4_NKu6qH8XOQ'