@baseUrl = http://34.8.66.38
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJjbGllbnRlIiwiZXhwIjoxNzQ0MTUzODE5fQ.hqMr3QixrvC6ZocJ6BpqatycDiqaDSo__B2nXBHzScA
curl --location '{{baseUrl}}/api/v1/ventas/procesador_pedidos/pedidos' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{token}}' \
--data '{
  "cliente_id": 3,
   "vendedor_id":null,
  "productos": [
    {
      "id": 1,
      "cantidad": 1,
      "precio_unitario": 50.0
    }
  ]
}'