
@baseUrl = http://34.8.66.38
curl --location '{{baseUrl}}/api/v1/ventas/procesador_pedidos/pedidos' \
--header 'Content-Type: application/json' \
--data '{
  "cliente_id": 123456,
  "vendedor_id": 987654,
  "productos": [
    {
      "id": 10,
      "cantidad": 10,
      "precio_unitario": 50.0
    },
    {
      "id": 2,
      "cantidad": 5,
      "precio_unitario": 120.0
    },
    {
      "id": 3,
      "cantidad": 8,
      "precio_unitario": 80.0
    }
  ]
}
'