@baseUrl = http://localhost:8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJkaXJlY3Rvci1jb21wcmFzIiwiZXhwIjoxNzQ1ODYzMzMwfQ.ieyKo7_bHY78cA1kOVYcRjTaCRimZIGei-0mzrGehEg
curl --location \
  --header "Authorization: Bearer {{token}}" \
  --request GET '{{baseUrl}}/api/v1/inventario/gestor_stock/productos'