@baseUrl = http://34.49.18.136
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInJvbGUiOiJ2ZW5kZWRvciIsImV4cCI6MTc0NDkzNDk0OH0.F_QsMLNGC8DUVggIxkKHbUH-E3yeSOjGBgTKUDISPmA

curl --location \
  --header "Authorization: Bearer {{token}}" \
  --request GET '{{baseUrl}}/api/v1/inventario/gestor_stock/productos'