@baseUrl = http://34.8.66.38

curl --request POST \
  --url {{baseUrl}}/api/v1/seguridad/gestor_usuarios/r/auth/login \
  --header 'content-type: application/json' \
  --data '{
  "email": "pepe@gmail.com",
  "password": "password"
}'