@baseUrl = http://34.8.175.2

curl --request POST \
  --url {{baseUrl}}/api/v1/seguridad/gestor_usuarios/r/auth/login \
  --header 'content-type: application/json' \
  --data '{
  "email": "testv@mail.com",
  "password": "test_password"
}'