name: Deploy Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   deploy_to_gke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message for 'CD'
        if: "contains(github.event.head_commit.message, 'CD')"
        run: echo "Commit message contains 'CD'. Proceeding with deployment."
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Activate Service Account
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: proyecto-final-2-454403
      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker
      - name: Build and Push Docker Images
        working-directory: backend/scripts/manejo_imagenes
        run: |
          chmod +x construir_todas_las_imagenes.sh
          ./construir_todas_las_imagenes.sh
          chmod +x subir_imagenes_a_gcp.sh
          ./subir_imagenes_a_gcp.sh
      - name: Connect to GKE Cluster
        working-directory: backend/scripts/gke
        run: |
          chmod +x conectarse_al_cluster.sh
          ./conectarse_al_cluster.sh
      - name: Deploy to GKE
        working-directory: backend/scripts/manejo_imagenes
        run: |
          chmod +x desplegar_imagenes_en_gke.sh
          ./desplegar_imagenes_en_gke.sh