name: Deploy Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   deploy_to_gke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message for 'CD'
        if: "contains(github.event.head_commit.message, 'CD')"
        run: echo "Commit message contains 'CD'. Proceeding with deployment."
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: proyecto-final-2-454403
      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker
      - name: Set up GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: prod-cluster-cpp-api
          location: us-central1-f
          project_id: proyecto-final-2-454403
      - name: Build and Push Docker Images
        working-directory: backend/scripts/manejo_imagenes
        run: |
          chmod +x construir_todas_las_imagenes.sh
          ./construir_todas_las_imagenes.sh
      - name: Publish Docker Images to GCP
        run: |-
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/compras_servicio/gestor_compras:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_productos:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_proveedores:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_stock:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/generador_reportes:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/generador_rutas_entrega:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/gestor_entregas:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/seguridad_servicio/gestor_usuarios:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/generador_reportes:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/gestor_ventas:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/procesador_pedidos:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/procesador_video:latest
      - name: Connect to GKE Cluster
        working-directory: backend/scripts/gke
        run: |
          chmod +x conectarse_al_cluster.sh
          ./conectarse_al_cluster.sh
      - name: Deploy to GKE
        working-directory: backend/scripts/manejo_imagenes
        run: |
          chmod +x desplegar_imagenes_en_gke.sh
          ./desplegar_imagenes_en_gke.sh