name: Deploy Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   deploy_to_gke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message for 'CD'
        if: "contains(github.event.head_commit.message, 'CD')"
        run: echo "Commit message contains 'CD'. Proceeding with deployment."
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: proyecto-final-2-454403
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Authenticate with GCP
        run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker
      - name: Build and Push Docker Images
        run: |
          chmod +x backend/scripts/manejo_imagenes/construir_todas_las_imagenes.sh
          backend/scripts/manejo_imagenes/construir_todas_las_imagenes.sh
          chmod +x backend/scripts/manejo_imagenes/subir_imagenes_a_gcp.sh
          backend/scripts/manejo_imagenes/subir_imagenes_a_gcp.sh
      - name: Connect to GKE Cluster
        run: |
          chmod +x backend/scripts/gke/conectarse_al_cluster.sh
          backend/scripts/gke/conectarse_al_cluster.sh
      - name: Deploy to GKE
        run: |
          chmod +x backend/scripts/manejo_imagenes/desplegar_imagenes_en_gke.sh
          backend/scripts/manejo_imagenes/desplegar_imagenes_en_gke.sh