name: Deploy Backend
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   deploy_to_gke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message for 'CD'
        if: "contains(github.event.head_commit.message, 'CD')"
        run: echo "Commit message contains 'CD'. Proceeding with deployment."
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: proyecto-final-2-454403
      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Set up GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: prod-cluster-cpp-api
          location: us-central1-f
          project_id: proyecto-final-2-454403
      - name: Build and Push Docker Images
        working-directory: backend/scripts/manejo_imagenes
        run: |
          chmod +x construir_todas_las_imagenes.sh
          ./construir_todas_las_imagenes.sh
      - name: Publish Docker Images to GCP
        run: |-
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/compras_servicio/gestor_compras:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_productos:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_proveedores:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/inventario_servicio/gestor_stock:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/generador_reportes:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/generador_rutas_entrega:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/logistica_servicio/gestor_entregas:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/seguridad_servicio/gestor_usuarios:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/generador_reportes:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/gestor_ventas:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/procesador_pedidos:latest
          docker push us-central1-docker.pkg.dev/proyecto-final-2-454403/repositorio-imagenes-docker/ventas_servicio/procesador_video:latest
      - name: Deploy to GKE
        working-directory: backend/scripts/manejo_imagenes
        run: |
          kubectl apply -f ../../k8s/compras_servicio_db_deployment.yaml
          kubectl apply -f ../../k8s/compras_servicio_db_service.yaml
          kubectl apply -f ../../k8s/logistica_servicio_db_deployment.yaml
          kubectl apply -f ../../k8s/logistica_servicio_db_service.yaml
          kubectl apply -f ../../k8s/seguridad_servicio_db_deployment.yaml
          kubectl apply -f ../../k8s/seguridad_servicio_db_service.yaml
          kubectl apply -f ../../k8s/ventas_servicio_db_deployment.yaml
          kubectl apply -f ../../k8s/ventas_servicio_db_service.yaml
          kubectl apply -f ../../k8s/inventario_servicio_db_deployment.yaml
          kubectl apply -f ../../k8s/inventario_servicio_db_service.yaml
          kubectl apply -f ../../k8s/pulsar_deployment.yaml
          kubectl apply -f ../../k8s/pulsar_service.yaml
          kubectl apply -f ../../k8s/gestor_compras_deployment.yaml
          kubectl apply -f ../../k8s/gestor_compras_service.yaml
          kubectl apply -f ../../k8s/gestor_productos_deployment.yaml
          kubectl apply -f ../../k8s/gestor_productos_service.yaml
          kubectl apply -f ../../k8s/gestor_proveedores_deployment.yaml
          kubectl apply -f ../../k8s/gestor_proveedores_service.yaml
          kubectl apply -f ../../k8s/gestor_stock_deployment.yaml
          kubectl apply -f ../../k8s/gestor_stock_service.yaml
          kubectl apply -f ../../k8s/generador_reportes_logistica_deployment.yaml
          kubectl apply -f ../../k8s/generador_reportes_logistica_service.yaml
          kubectl apply -f ../../k8s/generador_reportes_ventas_deployment.yaml
          kubectl apply -f ../../k8s/generador_reportes_ventas_service.yaml
          kubectl apply -f ../../k8s/gestor_rutas_entrega_deployment.yaml
          kubectl apply -f ../../k8s/gestor_rutas_entrega_service.yaml
          kubectl apply -f ../../k8s/gestor_entregas_deployment.yaml
          kubectl apply -f ../../k8s/gestor_entregas_service.yaml
          kubectl apply -f ../../k8s/gestor_usuarios_deployment.yaml
          kubectl apply -f ../../k8s/gestor_usuarios_service.yaml
          kubectl apply -f ../../k8s/gestor_ventas_deployment.yaml
          kubectl apply -f ../../k8s/gestor_ventas_service.yaml
          kubectl apply -f ../../k8s/procesador_pedidos_deployment.yaml
          kubectl apply -f ../../k8s/procesador_pedidos_service.yaml
          kubectl apply -f ../../k8s/procesador_video_deployment.yaml
          kubectl apply -f ../../k8s/procesador_video_service.yaml
          kubectl apply -f ../../k8s/ingress.yaml
          kubectl get pods