name: Test Backend
on:
  push:
    branches:
      - main
      - '**'
  pull_request:
    branches:
      - main
jobs:
  test_gestor_compras:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        working-directory: ./backend/compras_servicio/gestor_compras
        run: pip install pipenv
      - name: Install dependencies
        working-directory: ./backend/compras_servicio/gestor_compras
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/backend/compras_servicio/gestor_compras:$PWD/backend/seedwork_compartido" >> $GITHUB_ENV
      - name: Run unit tests
        working-directory: ./backend/compras_servicio/gestor_compras
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
        run: coverage run -m unittest discover
      - name: Run coverage report
        working-directory: ./backend/compras_servicio/gestor_compras
        run: coverage report --fail-under=70